on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.0, 7.1, 7.2, 7.3, 7.4, 8.0, 8.1]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, igbinary, msgpack
      - run: |
          phpize
          ./configure --enable-redis-lzf --enable-redis-igbinary --enable-redis-msgpack
          make install
      - run: |
          sudo add-apt-repository ppa:redislabs/redis
          sudo apt-get install redis
      - run: redis-server --port 0 --daemonize yes --aclfile tests/users.acl --unixsocket /tmp/redis.sock
      - run: |
          for PORT in $(seq 6379 6382) $(seq 32767 32769); do
            redis-server --port $PORT --daemonize yes --aclfile tests/users.acl
          done
      - run: |
          mkdir -p tests/nodes
          echo -n > tests/nodes/nodemap
          for PORT in $(seq 7000 7011); do
            redis-server --port $PORT --cluster-enabled yes --cluster-config-file $PORT.conf --daemonize yes --aclfile tests/users.acl
            echo 127.0.0.1:$PORT >> tests/nodes/nodemap
          done
          echo yes | redis-cli --cluster create $(seq -f 127.0.0.1:%g 7000 7011) --cluster-replicas 3 --user phpredis -a phpredis
      - run: php tests/TestRedis.php --class Redis --user phpredis --auth phpredis
      - run: php tests/TestRedis.php --class RedisArray
      - run: php tests/TestRedis.php --class RedisCluster
      - run: php tests/TestRedis.php --class RedisSentinel
